services:
  - type: web
    name: ai-api-proxy
    runtime: docker
    region: frankfurt
    plan: starter
    autoDeploy: false
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_API_KEY
        sync: false
